"""post

Revision ID: 5dd03ebf5448
Revises: 07abcab196d8
Create Date: 2024-02-29 23:13:27.779572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5dd03ebf5448'
down_revision: Union[str, None] = '07abcab196d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_column('social', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('social', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
